#define IDENTIFIER 1
#define CONSTANT 100
#define MAGIE 2
#define NEATA 3
#define NB 4
#define INFIDELE 5
#define BATUTE_IN_CUI 6
#define LANT 7
#define DE 8
#define IN_CAZ_CA 9
#define APAI 10
#define ALTCUM 11
#define CAT_TIMP 12
#define MUNCESTE 13
#define INGHITE 14
#define SCUIPA 15
#define STRING 16
#define BUCATICA 17
#define NUMAR 18
#define COMBINATIE 19
#define GATA 20
#define PLUS_CA 21
#define ORI 22
#define NU 23
